name: Handle new issue
on:
  issues:
    types: [opened, reopened]
jobs:
  tg_message:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHANNEL_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.event.issue.user.login }} created new issue "${{ github.event.issue.title }}"
            See more by https://github.com/${{ github.repository }}/issues/${{ github.event.issue.number }}
  issue_labels:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Add "inbox" and "new" labels to the issue
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: |
            inbox
            new
